// generated by tools/gen_fuzz.py: do not edit by hand
#include "doctest.h"
#include "alloc_guard.hpp"
#include "tu.hpp"
#include <random>
#include <type_traits>
#include "cr01/cr01.hpp"
#include "cr02/cr02.hpp"
#include "cr03/cr03.hpp"
#include "cr04/cr04.hpp"
#include "cr05/cr05.hpp"
#include "cr06/cr06.hpp"
#include "cs01/cs01.hpp"
#include "cs02/cs02.hpp"
#include "cs03/cs03.hpp"
#include "cs04/cs04.hpp"
#include "dl01/dl01.hpp"
#include "dl02/dl02.hpp"
#include "dl03/dl03.hpp"
#include "dl04/dl04.hpp"
#include "dl05/dl05.hpp"
#include "dy01/dy01.hpp"
#include "dy02/dy02.hpp"
#include "dy03/dy03.hpp"
#include "dy04/dy04.hpp"
#include "dy05/dy05.hpp"
#include "dy06/dy06.hpp"
#include "dy07/dy07.hpp"
#include "dy08/dy08.hpp"
#include "dy09/dy09.hpp"
#include "dy10/dy10.hpp"
#include "dy11/dy11.hpp"
#include "dy12/dy12.hpp"
#include "eq01/eq01.hpp"
#include "eq02/eq02.hpp"
#include "eq03/eq03.hpp"
#include "eq04/eq04.hpp"
#include "eq05/eq05.hpp"
#include "eq06/eq06.hpp"
#include "eq07/eq07.hpp"
#include "eq08/eq08.hpp"
#include "eq09/eq09.hpp"
#include "gt01/gt01.hpp"
#include "gt02/gt02.hpp"
#include "gt03/gt03.hpp"
#include "gt04/gt04.hpp"
#include "gt05/gt05.hpp"
#include "lo01/lo01.hpp"
#include "lo02/lo02.hpp"
#include "lo03/lo03.hpp"
#include "lv01/lv01.hpp"
#include "lv02/lv02.hpp"
#include "lv03/lv03.hpp"
#include "lv04/lv04.hpp"
#include "lv05/lv05.hpp"
#include "lv06/lv06.hpp"
#include "lv07/lv07.hpp"
#include "lv08/lv08.hpp"
#include "lv09/lv09.hpp"
#include "lv10/lv10.hpp"
#include "lv11/lv11.hpp"
#include "lv12/lv12.hpp"
#include "lv13/lv13.hpp"
#include "lv14/lv14.hpp"
#include "lv15/lv15.hpp"
#include "lv16/lv16.hpp"
#include "lv17/lv17.hpp"
#include "lv18/lv18.hpp"
#include "lv19/lv19.hpp"
#include "lv20/lv20.hpp"
#include "lv21/lv21.hpp"
#include "lv22/lv22.hpp"
#include "lv23/lv23.hpp"
#include "lv24/lv24.hpp"
#include "lv25/lv25.hpp"
#include "lv26/lv26.hpp"
#include "lv27/lv27.hpp"
#include "lv28/lv28.hpp"
#include "lv29/lv29.hpp"
#include "lv30/lv30.hpp"
#include "md01/md01.hpp"
#include "md02/md02.hpp"
#include "md03/md03.hpp"
#include "md04/md04.hpp"
#include "md05/md05.hpp"
#include "md06/md06.hpp"
#include "md07/md07.hpp"
#include "ms01/ms01.hpp"
#include "ms02/ms02.hpp"
#include "ms03/ms03.hpp"
#include "ms04/ms04.hpp"
#include "ms05/ms05.hpp"
#include "ms06/ms06.hpp"
#include "ms07/ms07.hpp"
#include "mt01/mt01.hpp"
#include "mt02/mt02.hpp"
#include "mt03/mt03.hpp"
#include "mt04/mt04.hpp"
#include "mt05/mt05.hpp"
#include "rs01/rs01.hpp"
#include "rs03/rs03.hpp"
#include "rs04/rs04.hpp"
#include "rs05/rs05.hpp"
#include "rs06/rs06.hpp"
#include "rs07/rs07.hpp"
#include "rv01/rv01.hpp"
#include "rv02/rv02.hpp"
#include "rv03/rv03.hpp"
#include "rv04/rv04.hpp"
#include "rv05/rv05.hpp"
#include "rv06/rv06.hpp"
#include "rv07/rv07.hpp"
#include "rv08/rv08.hpp"
#include "sa01/sa01.hpp"
#include "sa02/sa02.hpp"
#include "sa03/sa03.hpp"
#include "sa04/sa04.hpp"
#include "sa05/sa05.hpp"
#include "sa06/sa06.hpp"
#include "sa07/sa07.hpp"
#include "sa08/sa08.hpp"
#include "st01/st01.hpp"
#include "st02/st02.hpp"
#include "st03/st03.hpp"
#include "st04/st04.hpp"
#include "st05/st05.hpp"
#include "st06/st06.hpp"
#include "ut01/ut01.hpp"
#include "ut02/ut02.hpp"
#include "ut03/ut03.hpp"
#include "vo01/vo01.hpp"
#include "vo02/vo02.hpp"
#include "vo03/vo03.hpp"
#include "vo04/vo04.hpp"
#include "vo05/vo05.hpp"
#include "vo06/vo06.hpp"
#include "vo07/vo07.hpp"
#include "vo08/vo08.hpp"

namespace {
template <class C, class = void> struct HasTempo : std::false_type {};
template <class C> struct HasTempo<C, std::void_t<decltype(std::declval<C&>().setTempo(120.0))>> : std::true_type {};
template <class C, class = void> struct HasSc : std::false_type {};
template <class C> struct HasSc<C, std::void_t<decltype(std::declval<C&>().processWithSidechain(std::declval<float**>(), 0, 0, std::declval<const float* const*>(), 0))>> : std::true_type {};
template <class C, class = void> struct HasReset : std::false_type {};
template <class C> struct HasReset<C, std::void_t<decltype(std::declval<C&>().reset())>> : std::true_type {};
template <class C, class = void> struct HasTail : std::false_type {};
template <class C> struct HasTail<C, std::void_t<decltype(std::declval<const C&>().tailSeconds())>> : std::true_type {};
template <class C, class = void> struct HasWrites : std::false_type {};
template <class C> struct HasWrites<C, std::void_t<decltype(std::declval<C&>().takeParamWrite(std::declval<int&>(), std::declval<double&>()))>> : std::true_type {};

// prepare, two blocks to start, then (counted) rounds of: a few parameters set to values anywhere in their range (the adapter sets them on the audio thread), four blocks of noise (with a sidechain where the product has one)
template <class P> long allocations(const std::vector<sw::ParamSpec>& specs, unsigned seed, double fs) {
    std::mt19937 rng(seed);
    P p; p.prepare(fs, 256);
    if constexpr (HasTempo<P>::value) p.setTempo(97.0);
    p.snapToTargets();
    std::vector<float> l(256), r(256);
    auto block = [&]() {
        for (int i = 0; i < 256; ++i) { l[static_cast<size_t>(i)] = static_cast<float>(std::uniform_real_distribution<>(-0.5, 0.5)(rng)); r[static_cast<size_t>(i)] = l[static_cast<size_t>(i)] * 0.5f; }
        float* c[2] = {l.data(), r.data()};
        if constexpr (HasSc<P>::value) { const float* sc[2] = {r.data(), l.data()}; p.processWithSidechain(c, 2, 256, sc, 2); }
        else p.process(c, 2, 256);
    };
    block(); block();
    allocguard::Scope guard;
    for (int round = 0; round < 60; ++round) {
        for (int k = 0; k < 4; ++k) {
            const size_t i = rng() % specs.size();
            double v = specs[i].min + (specs[i].max - specs[i].min) * std::uniform_real_distribution<>(0, 1)(rng);
            if (specs[i].curve == sw::Curve::Step) v = specs[i].steps[rng() % specs[i].steps.size()];
            p.setParam(static_cast<int>(i), v);
        }
        for (int b = 0; b < 4; ++b) block();
        // what the adapter also does on the audio thread: the write queue, the tail, a reset (the host stopped or jumped)
        if constexpr (HasWrites<P>::value) { int id; double v; while (p.takeParamWrite(id, v) != 0) {} }
        if constexpr (HasTail<P>::value) { volatile double t = p.tailSeconds(); (void)t; }
        if constexpr (HasReset<P>::value) { if (round % 7 == 3) p.reset(); }
    }
    return guard.n();
}
}

TEST_CASE("the audio thread does not allocate: cr01") { CHECK(allocations<sw::cr01::Processor>(sw::cr01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::cr01::Processor>(sw::cr01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: cr02") { CHECK(allocations<sw::cr02::Processor>(sw::cr02::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::cr02::Processor>(sw::cr02::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: cr03") { CHECK(allocations<sw::cr03::Processor>(sw::cr03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::cr03::Processor>(sw::cr03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: cr04") { CHECK(allocations<sw::cr04::Processor>(sw::cr04::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::cr04::Processor>(sw::cr04::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: cr05") { CHECK(allocations<sw::cr05::Processor>(sw::cr05::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::cr05::Processor>(sw::cr05::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: cr06") { CHECK(allocations<sw::cr06::Processor>(sw::cr06::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::cr06::Processor>(sw::cr06::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: cs01") { CHECK(allocations<sw::cs01::Processor>(sw::cs01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::cs01::Processor>(sw::cs01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: cs02") { CHECK(allocations<sw::cs02::Processor>(sw::cs02::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::cs02::Processor>(sw::cs02::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: cs03") { CHECK(allocations<sw::cs03::Processor>(sw::cs03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::cs03::Processor>(sw::cs03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: cs04") { CHECK(allocations<sw::cs04::Processor>(sw::cs04::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::cs04::Processor>(sw::cs04::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dl01") { CHECK(allocations<sw::dl01::Processor>(sw::dl01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dl01::Processor>(sw::dl01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dl02") { CHECK(allocations<sw::dl02::Processor>(sw::dl02::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dl02::Processor>(sw::dl02::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dl03") { CHECK(allocations<sw::dl03::Processor>(sw::dl03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dl03::Processor>(sw::dl03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dl04") { CHECK(allocations<sw::dl04::Processor>(sw::dl04::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dl04::Processor>(sw::dl04::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dl05") { CHECK(allocations<sw::dl05::Processor>(sw::dl05::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dl05::Processor>(sw::dl05::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dy01") { CHECK(allocations<sw::dy01::Processor>(sw::dy01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dy01::Processor>(sw::dy01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dy02") { CHECK(allocations<sw::dy02::Processor>(sw::dy02::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dy02::Processor>(sw::dy02::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dy03") { CHECK(allocations<sw::dy03::Processor>(sw::dy03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dy03::Processor>(sw::dy03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dy04") { CHECK(allocations<sw::dy04::Processor>(sw::dy04::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dy04::Processor>(sw::dy04::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dy05") { CHECK(allocations<sw::dy05::Processor>(sw::dy05::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dy05::Processor>(sw::dy05::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dy06") { CHECK(allocations<sw::dy06::Processor>(sw::dy06::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dy06::Processor>(sw::dy06::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dy07") { CHECK(allocations<sw::dy07::Processor>(sw::dy07::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dy07::Processor>(sw::dy07::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dy08") { CHECK(allocations<sw::dy08::Processor>(sw::dy08::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dy08::Processor>(sw::dy08::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dy09") { CHECK(allocations<sw::dy09::Processor>(sw::dy09::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dy09::Processor>(sw::dy09::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dy10") { CHECK(allocations<sw::dy10::Processor>(sw::dy10::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dy10::Processor>(sw::dy10::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dy11") { CHECK(allocations<sw::dy11::Processor>(sw::dy11::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dy11::Processor>(sw::dy11::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: dy12") { CHECK(allocations<sw::dy12::Processor>(sw::dy12::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::dy12::Processor>(sw::dy12::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: eq01") { CHECK(allocations<sw::eq01::Processor>(sw::eq01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::eq01::Processor>(sw::eq01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: eq02") { CHECK(allocations<sw::eq02::Processor>(sw::eq02::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::eq02::Processor>(sw::eq02::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: eq03") { CHECK(allocations<sw::eq03::Processor>(sw::eq03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::eq03::Processor>(sw::eq03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: eq04") { CHECK(allocations<sw::eq04::Processor>(sw::eq04::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::eq04::Processor>(sw::eq04::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: eq05") { CHECK(allocations<sw::eq05::Processor>(sw::eq05::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::eq05::Processor>(sw::eq05::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: eq06") { CHECK(allocations<sw::eq06::Processor>(sw::eq06::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::eq06::Processor>(sw::eq06::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: eq07") { CHECK(allocations<sw::eq07::Processor>(sw::eq07::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::eq07::Processor>(sw::eq07::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: eq08") { CHECK(allocations<sw::eq08::Processor>(sw::eq08::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::eq08::Processor>(sw::eq08::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: eq09") { CHECK(allocations<sw::eq09::Processor>(sw::eq09::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::eq09::Processor>(sw::eq09::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: gt01") { CHECK(allocations<sw::gt01::Processor>(sw::gt01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::gt01::Processor>(sw::gt01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: gt02") { CHECK(allocations<sw::gt02::Processor>(sw::gt02::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::gt02::Processor>(sw::gt02::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: gt03") { CHECK(allocations<sw::gt03::Processor>(sw::gt03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::gt03::Processor>(sw::gt03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: gt04") { CHECK(allocations<sw::gt04::Processor>(sw::gt04::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::gt04::Processor>(sw::gt04::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: gt05") { CHECK(allocations<sw::gt05::Processor>(sw::gt05::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::gt05::Processor>(sw::gt05::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lo01") { CHECK(allocations<sw::lo01::Processor>(sw::lo01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lo01::Processor>(sw::lo01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lo02") { CHECK(allocations<sw::lo02::Processor>(sw::lo02::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lo02::Processor>(sw::lo02::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lo03") { CHECK(allocations<sw::lo03::Processor>(sw::lo03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lo03::Processor>(sw::lo03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv01") { CHECK(allocations<sw::lv01::Processor>(sw::lv01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv01::Processor>(sw::lv01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv02") { CHECK(allocations<sw::lv02::Processor>(sw::lv02::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv02::Processor>(sw::lv02::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv03") { CHECK(allocations<sw::lv03::Processor>(sw::lv03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv03::Processor>(sw::lv03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv04") { CHECK(allocations<sw::lv04::Processor>(sw::lv04::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv04::Processor>(sw::lv04::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv05") { CHECK(allocations<sw::lv05::Processor>(sw::lv05::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv05::Processor>(sw::lv05::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv06") { CHECK(allocations<sw::lv06::Processor>(sw::lv06::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv06::Processor>(sw::lv06::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv07") { CHECK(allocations<sw::lv07::Processor>(sw::lv07::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv07::Processor>(sw::lv07::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv08") { CHECK(allocations<sw::lv08::Processor>(sw::lv08::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv08::Processor>(sw::lv08::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv09") { CHECK(allocations<sw::lv09::Processor>(sw::lv09::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv09::Processor>(sw::lv09::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv10") { CHECK(allocations<sw::lv10::Processor>(sw::lv10::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv10::Processor>(sw::lv10::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv11") { CHECK(allocations<sw::lv11::Processor>(sw::lv11::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv11::Processor>(sw::lv11::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv12") { CHECK(allocations<sw::lv12::Processor>(sw::lv12::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv12::Processor>(sw::lv12::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv13") { CHECK(allocations<sw::lv13::Processor>(sw::lv13::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv13::Processor>(sw::lv13::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv14") { CHECK(allocations<sw::lv14::Processor>(sw::lv14::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv14::Processor>(sw::lv14::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv15") { CHECK(allocations<sw::lv15::Processor>(sw::lv15::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv15::Processor>(sw::lv15::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv16") { CHECK(allocations<sw::lv16::Processor>(sw::lv16::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv16::Processor>(sw::lv16::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv17") { CHECK(allocations<sw::lv17::Processor>(sw::lv17::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv17::Processor>(sw::lv17::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv18") { CHECK(allocations<sw::lv18::Processor>(sw::lv18::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv18::Processor>(sw::lv18::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv19") { CHECK(allocations<sw::lv19::Processor>(sw::lv19::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv19::Processor>(sw::lv19::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv20") { CHECK(allocations<sw::lv20::Processor>(sw::lv20::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv20::Processor>(sw::lv20::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv21") { CHECK(allocations<sw::lv21::Processor>(sw::lv21::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv21::Processor>(sw::lv21::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv22") { CHECK(allocations<sw::lv22::Processor>(sw::lv22::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv22::Processor>(sw::lv22::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv23") { CHECK(allocations<sw::lv23::Processor>(sw::lv23::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv23::Processor>(sw::lv23::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv24") { CHECK(allocations<sw::lv24::Processor>(sw::lv24::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv24::Processor>(sw::lv24::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv25") { CHECK(allocations<sw::lv25::Processor>(sw::lv25::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv25::Processor>(sw::lv25::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv26") { CHECK(allocations<sw::lv26::Processor>(sw::lv26::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv26::Processor>(sw::lv26::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv27") { CHECK(allocations<sw::lv27::Processor>(sw::lv27::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv27::Processor>(sw::lv27::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv28") { CHECK(allocations<sw::lv28::Processor>(sw::lv28::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv28::Processor>(sw::lv28::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv29") { CHECK(allocations<sw::lv29::Processor>(sw::lv29::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv29::Processor>(sw::lv29::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: lv30") { CHECK(allocations<sw::lv30::Processor>(sw::lv30::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::lv30::Processor>(sw::lv30::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: md01") { CHECK(allocations<sw::md01::Processor>(sw::md01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::md01::Processor>(sw::md01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: md02") { CHECK(allocations<sw::md02::Processor>(sw::md02::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::md02::Processor>(sw::md02::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: md03") { CHECK(allocations<sw::md03::Processor>(sw::md03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::md03::Processor>(sw::md03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: md04") { CHECK(allocations<sw::md04::Processor>(sw::md04::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::md04::Processor>(sw::md04::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: md05") { CHECK(allocations<sw::md05::Processor>(sw::md05::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::md05::Processor>(sw::md05::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: md06") { CHECK(allocations<sw::md06::Processor>(sw::md06::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::md06::Processor>(sw::md06::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: md07") { CHECK(allocations<sw::md07::Processor>(sw::md07::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::md07::Processor>(sw::md07::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: ms01") { CHECK(allocations<sw::ms01::Processor>(sw::ms01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::ms01::Processor>(sw::ms01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: ms02") { CHECK(allocations<sw::ms02::Processor>(sw::ms02::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::ms02::Processor>(sw::ms02::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: ms03") { CHECK(allocations<sw::ms03::Processor>(sw::ms03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::ms03::Processor>(sw::ms03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: ms04") { CHECK(allocations<sw::ms04::Processor>(sw::ms04::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::ms04::Processor>(sw::ms04::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: ms05") { CHECK(allocations<sw::ms05::Processor>(sw::ms05::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::ms05::Processor>(sw::ms05::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: ms06") { CHECK(allocations<sw::ms06::Processor>(sw::ms06::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::ms06::Processor>(sw::ms06::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: ms07") { CHECK(allocations<sw::ms07::Processor>(sw::ms07::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::ms07::Processor>(sw::ms07::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: mt01") { CHECK(allocations<sw::mt01::Processor>(sw::mt01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::mt01::Processor>(sw::mt01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: mt02") { CHECK(allocations<sw::mt02::Processor>(sw::mt02::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::mt02::Processor>(sw::mt02::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: mt03") { CHECK(allocations<sw::mt03::Processor>(sw::mt03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::mt03::Processor>(sw::mt03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: mt04") { CHECK(allocations<sw::mt04::Processor>(sw::mt04::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::mt04::Processor>(sw::mt04::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: mt05") { CHECK(allocations<sw::mt05::Processor>(sw::mt05::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::mt05::Processor>(sw::mt05::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: rs01") { CHECK(allocations<sw::rs01::Processor>(sw::rs01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::rs01::Processor>(sw::rs01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: rs03") { CHECK(allocations<sw::rs03::Processor>(sw::rs03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::rs03::Processor>(sw::rs03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: rs04") { CHECK(allocations<sw::rs04::Processor>(sw::rs04::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::rs04::Processor>(sw::rs04::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: rs05") { CHECK(allocations<sw::rs05::Processor>(sw::rs05::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::rs05::Processor>(sw::rs05::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: rs06") { CHECK(allocations<sw::rs06::Processor>(sw::rs06::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::rs06::Processor>(sw::rs06::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: rs07") { CHECK(allocations<sw::rs07::Processor>(sw::rs07::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::rs07::Processor>(sw::rs07::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: rv01") { CHECK(allocations<sw::rv01::Processor>(sw::rv01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::rv01::Processor>(sw::rv01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: rv02") { CHECK(allocations<sw::rv02::Processor>(sw::rv02::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::rv02::Processor>(sw::rv02::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: rv03") { CHECK(allocations<sw::rv03::Processor>(sw::rv03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::rv03::Processor>(sw::rv03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: rv04") { CHECK(allocations<sw::rv04::Processor>(sw::rv04::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::rv04::Processor>(sw::rv04::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: rv05") { CHECK(allocations<sw::rv05::Processor>(sw::rv05::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::rv05::Processor>(sw::rv05::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: rv06") { CHECK(allocations<sw::rv06::Processor>(sw::rv06::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::rv06::Processor>(sw::rv06::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: rv07") { CHECK(allocations<sw::rv07::Processor>(sw::rv07::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::rv07::Processor>(sw::rv07::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: rv08") { CHECK(allocations<sw::rv08::Processor>(sw::rv08::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::rv08::Processor>(sw::rv08::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: sa01") { CHECK(allocations<sw::sa01::Processor>(sw::sa01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::sa01::Processor>(sw::sa01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: sa02") { CHECK(allocations<sw::sa02::Processor>(sw::sa02::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::sa02::Processor>(sw::sa02::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: sa03") { CHECK(allocations<sw::sa03::Processor>(sw::sa03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::sa03::Processor>(sw::sa03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: sa04") { CHECK(allocations<sw::sa04::Processor>(sw::sa04::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::sa04::Processor>(sw::sa04::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: sa05") { CHECK(allocations<sw::sa05::Processor>(sw::sa05::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::sa05::Processor>(sw::sa05::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: sa06") { CHECK(allocations<sw::sa06::Processor>(sw::sa06::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::sa06::Processor>(sw::sa06::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: sa07") { CHECK(allocations<sw::sa07::Processor>(sw::sa07::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::sa07::Processor>(sw::sa07::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: sa08") { CHECK(allocations<sw::sa08::Processor>(sw::sa08::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::sa08::Processor>(sw::sa08::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: st01") { CHECK(allocations<sw::st01::Processor>(sw::st01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::st01::Processor>(sw::st01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: st02") { CHECK(allocations<sw::st02::Processor>(sw::st02::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::st02::Processor>(sw::st02::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: st03") { CHECK(allocations<sw::st03::Processor>(sw::st03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::st03::Processor>(sw::st03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: st04") { CHECK(allocations<sw::st04::Processor>(sw::st04::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::st04::Processor>(sw::st04::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: st05") { CHECK(allocations<sw::st05::Processor>(sw::st05::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::st05::Processor>(sw::st05::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: st06") { CHECK(allocations<sw::st06::Processor>(sw::st06::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::st06::Processor>(sw::st06::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: ut01") { CHECK(allocations<sw::ut01::Processor>(sw::ut01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::ut01::Processor>(sw::ut01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: ut02") { CHECK(allocations<sw::ut02::Processor>(sw::ut02::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::ut02::Processor>(sw::ut02::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: ut03") { CHECK(allocations<sw::ut03::Processor>(sw::ut03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::ut03::Processor>(sw::ut03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: vo01") { CHECK(allocations<sw::vo01::Processor>(sw::vo01::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::vo01::Processor>(sw::vo01::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: vo02") { CHECK(allocations<sw::vo02::Processor>(sw::vo02::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::vo02::Processor>(sw::vo02::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: vo03") { CHECK(allocations<sw::vo03::Processor>(sw::vo03::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::vo03::Processor>(sw::vo03::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: vo04") { CHECK(allocations<sw::vo04::Processor>(sw::vo04::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::vo04::Processor>(sw::vo04::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: vo05") { CHECK(allocations<sw::vo05::Processor>(sw::vo05::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::vo05::Processor>(sw::vo05::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: vo06") { CHECK(allocations<sw::vo06::Processor>(sw::vo06::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::vo06::Processor>(sw::vo06::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: vo07") { CHECK(allocations<sw::vo07::Processor>(sw::vo07::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::vo07::Processor>(sw::vo07::specs(), 9u, 96000.0) == 0); }
TEST_CASE("the audio thread does not allocate: vo08") { CHECK(allocations<sw::vo08::Processor>(sw::vo08::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::vo08::Processor>(sw::vo08::specs(), 9u, 96000.0) == 0); }
