// generated by tools/gen_fuzz.py: do not edit by hand
#include "doctest.h"
#include "tu.hpp"
#include <random>
#include <type_traits>
#include "cs01/cs01.hpp"
#include "cs02/cs02.hpp"
#include "cs03/cs03.hpp"
#include "cs04/cs04.hpp"
#include "dl01/dl01.hpp"
#include "dl02/dl02.hpp"
#include "dl03/dl03.hpp"
#include "dl04/dl04.hpp"
#include "dl05/dl05.hpp"
#include "dy01/dy01.hpp"
#include "dy02/dy02.hpp"
#include "dy03/dy03.hpp"
#include "dy04/dy04.hpp"
#include "dy05/dy05.hpp"
#include "dy06/dy06.hpp"
#include "dy07/dy07.hpp"
#include "dy08/dy08.hpp"
#include "dy09/dy09.hpp"
#include "dy10/dy10.hpp"
#include "dy11/dy11.hpp"
#include "dy12/dy12.hpp"
#include "eq01/eq01.hpp"
#include "eq02/eq02.hpp"
#include "eq03/eq03.hpp"
#include "eq04/eq04.hpp"
#include "eq05/eq05.hpp"
#include "eq06/eq06.hpp"
#include "eq07/eq07.hpp"
#include "eq08/eq08.hpp"
#include "eq09/eq09.hpp"
#include "gt01/gt01.hpp"
#include "gt02/gt02.hpp"
#include "gt04/gt04.hpp"
#include "gt05/gt05.hpp"
#include "lo01/lo01.hpp"
#include "lo02/lo02.hpp"
#include "lo03/lo03.hpp"
#include "lv04/lv04.hpp"
#include "lv16/lv16.hpp"
#include "lv17/lv17.hpp"
#include "md01/md01.hpp"
#include "md02/md02.hpp"
#include "md03/md03.hpp"
#include "ms01/ms01.hpp"
#include "ms02/ms02.hpp"
#include "ms03/ms03.hpp"
#include "ms04/ms04.hpp"
#include "ms05/ms05.hpp"
#include "ms06/ms06.hpp"
#include "ms07/ms07.hpp"
#include "rv01/rv01.hpp"
#include "rv02/rv02.hpp"
#include "rv03/rv03.hpp"
#include "rv04/rv04.hpp"
#include "rv05/rv05.hpp"
#include "rv06/rv06.hpp"
#include "rv07/rv07.hpp"
#include "rv08/rv08.hpp"
#include "sa01/sa01.hpp"
#include "sa02/sa02.hpp"
#include "sa03/sa03.hpp"
#include "sa04/sa04.hpp"
#include "sa05/sa05.hpp"
#include "sa06/sa06.hpp"
#include "sa07/sa07.hpp"
#include "sa08/sa08.hpp"

namespace {
template <class C, class = void> struct HasTempo : std::false_type {};
template <class C> struct HasTempo<C, std::void_t<decltype(std::declval<C&>().setTempo(120.0))>> : std::true_type {};
template <class C, class = void> struct HasSc : std::false_type {};
template <class C> struct HasSc<C, std::void_t<decltype(std::declval<C&>().processWithSidechain(std::declval<float**>(), 0, 0, std::declval<const float* const*>(), 0))>> : std::true_type {};

// parameters at their ends (and the steps), a few buffers of noise, several rounds: the output must stay finite and sane
template <class P> void fuzzBounds(const std::vector<sw::ParamSpec>& specs, unsigned seed) {
    std::mt19937 rng(seed);
    for (double fs : {44100.0, 48000.0}) {
        P p;
        p.prepare(fs, 256);
        if constexpr (HasTempo<P>::value) p.setTempo(97.0);
        std::vector<float> l(256), r(256);
        for (int round = 0; round < 10; ++round) {
            for (size_t i = 0; i < specs.size(); ++i) {
                double v = (rng() & 1) ? specs[i].max : specs[i].min;
                if (specs[i].curve == sw::Curve::Step) v = specs[i].steps[rng() % specs[i].steps.size()];
                p.setParam(static_cast<int>(i), v);
            }
            if (round == 0) p.snapToTargets();
            for (int b = 0; b < 3; ++b) {
                for (int i = 0; i < 256; ++i) { l[static_cast<size_t>(i)] = static_cast<float>(std::uniform_real_distribution<>(-1, 1)(rng)); r[static_cast<size_t>(i)] = l[static_cast<size_t>(i)] * 0.5f; }
                float* c[2] = {l.data(), r.data()};
                if constexpr (HasSc<P>::value) { const float* sc[2] = {r.data(), l.data()}; p.processWithSidechain(c, 2, 256, sc, 2); }
                else p.process(c, 2, 256);
                for (int i = 0; i < 256; ++i) { REQUIRE(std::isfinite(l[static_cast<size_t>(i)])); REQUIRE(std::isfinite(r[static_cast<size_t>(i)])); REQUIRE(std::abs(l[static_cast<size_t>(i)]) < 1e10f); }
            }
        }
    }
}
}

TEST_CASE("fuzz parameter bounds: cs01") { fuzzBounds<sw::cs01::Processor>(sw::cs01::specs(), 17u); fuzzBounds<sw::cs01::Processor>(sw::cs01::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: cs02") { fuzzBounds<sw::cs02::Processor>(sw::cs02::specs(), 17u); fuzzBounds<sw::cs02::Processor>(sw::cs02::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: cs03") { fuzzBounds<sw::cs03::Processor>(sw::cs03::specs(), 17u); fuzzBounds<sw::cs03::Processor>(sw::cs03::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: cs04") { fuzzBounds<sw::cs04::Processor>(sw::cs04::specs(), 17u); fuzzBounds<sw::cs04::Processor>(sw::cs04::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dl01") { fuzzBounds<sw::dl01::Processor>(sw::dl01::specs(), 17u); fuzzBounds<sw::dl01::Processor>(sw::dl01::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dl02") { fuzzBounds<sw::dl02::Processor>(sw::dl02::specs(), 17u); fuzzBounds<sw::dl02::Processor>(sw::dl02::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dl03") { fuzzBounds<sw::dl03::Processor>(sw::dl03::specs(), 17u); fuzzBounds<sw::dl03::Processor>(sw::dl03::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dl04") { fuzzBounds<sw::dl04::Processor>(sw::dl04::specs(), 17u); fuzzBounds<sw::dl04::Processor>(sw::dl04::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dl05") { fuzzBounds<sw::dl05::Processor>(sw::dl05::specs(), 17u); fuzzBounds<sw::dl05::Processor>(sw::dl05::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dy01") { fuzzBounds<sw::dy01::Processor>(sw::dy01::specs(), 17u); fuzzBounds<sw::dy01::Processor>(sw::dy01::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dy02") { fuzzBounds<sw::dy02::Processor>(sw::dy02::specs(), 17u); fuzzBounds<sw::dy02::Processor>(sw::dy02::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dy03") { fuzzBounds<sw::dy03::Processor>(sw::dy03::specs(), 17u); fuzzBounds<sw::dy03::Processor>(sw::dy03::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dy04") { fuzzBounds<sw::dy04::Processor>(sw::dy04::specs(), 17u); fuzzBounds<sw::dy04::Processor>(sw::dy04::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dy05") { fuzzBounds<sw::dy05::Processor>(sw::dy05::specs(), 17u); fuzzBounds<sw::dy05::Processor>(sw::dy05::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dy06") { fuzzBounds<sw::dy06::Processor>(sw::dy06::specs(), 17u); fuzzBounds<sw::dy06::Processor>(sw::dy06::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dy07") { fuzzBounds<sw::dy07::Processor>(sw::dy07::specs(), 17u); fuzzBounds<sw::dy07::Processor>(sw::dy07::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dy08") { fuzzBounds<sw::dy08::Processor>(sw::dy08::specs(), 17u); fuzzBounds<sw::dy08::Processor>(sw::dy08::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dy09") { fuzzBounds<sw::dy09::Processor>(sw::dy09::specs(), 17u); fuzzBounds<sw::dy09::Processor>(sw::dy09::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dy10") { fuzzBounds<sw::dy10::Processor>(sw::dy10::specs(), 17u); fuzzBounds<sw::dy10::Processor>(sw::dy10::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dy11") { fuzzBounds<sw::dy11::Processor>(sw::dy11::specs(), 17u); fuzzBounds<sw::dy11::Processor>(sw::dy11::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: dy12") { fuzzBounds<sw::dy12::Processor>(sw::dy12::specs(), 17u); fuzzBounds<sw::dy12::Processor>(sw::dy12::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: eq01") { fuzzBounds<sw::eq01::Processor>(sw::eq01::specs(), 17u); fuzzBounds<sw::eq01::Processor>(sw::eq01::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: eq02") { fuzzBounds<sw::eq02::Processor>(sw::eq02::specs(), 17u); fuzzBounds<sw::eq02::Processor>(sw::eq02::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: eq03") { fuzzBounds<sw::eq03::Processor>(sw::eq03::specs(), 17u); fuzzBounds<sw::eq03::Processor>(sw::eq03::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: eq04") { fuzzBounds<sw::eq04::Processor>(sw::eq04::specs(), 17u); fuzzBounds<sw::eq04::Processor>(sw::eq04::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: eq05") { fuzzBounds<sw::eq05::Processor>(sw::eq05::specs(), 17u); fuzzBounds<sw::eq05::Processor>(sw::eq05::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: eq06") { fuzzBounds<sw::eq06::Processor>(sw::eq06::specs(), 17u); fuzzBounds<sw::eq06::Processor>(sw::eq06::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: eq07") { fuzzBounds<sw::eq07::Processor>(sw::eq07::specs(), 17u); fuzzBounds<sw::eq07::Processor>(sw::eq07::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: eq08") { fuzzBounds<sw::eq08::Processor>(sw::eq08::specs(), 17u); fuzzBounds<sw::eq08::Processor>(sw::eq08::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: eq09") { fuzzBounds<sw::eq09::Processor>(sw::eq09::specs(), 17u); fuzzBounds<sw::eq09::Processor>(sw::eq09::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: gt01") { fuzzBounds<sw::gt01::Processor>(sw::gt01::specs(), 17u); fuzzBounds<sw::gt01::Processor>(sw::gt01::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: gt02") { fuzzBounds<sw::gt02::Processor>(sw::gt02::specs(), 17u); fuzzBounds<sw::gt02::Processor>(sw::gt02::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: gt04") { fuzzBounds<sw::gt04::Processor>(sw::gt04::specs(), 17u); fuzzBounds<sw::gt04::Processor>(sw::gt04::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: gt05") { fuzzBounds<sw::gt05::Processor>(sw::gt05::specs(), 17u); fuzzBounds<sw::gt05::Processor>(sw::gt05::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: lo01") { fuzzBounds<sw::lo01::Processor>(sw::lo01::specs(), 17u); fuzzBounds<sw::lo01::Processor>(sw::lo01::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: lo02") { fuzzBounds<sw::lo02::Processor>(sw::lo02::specs(), 17u); fuzzBounds<sw::lo02::Processor>(sw::lo02::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: lo03") { fuzzBounds<sw::lo03::Processor>(sw::lo03::specs(), 17u); fuzzBounds<sw::lo03::Processor>(sw::lo03::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: lv04") { fuzzBounds<sw::lv04::Processor>(sw::lv04::specs(), 17u); fuzzBounds<sw::lv04::Processor>(sw::lv04::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: lv16") { fuzzBounds<sw::lv16::Processor>(sw::lv16::specs(), 17u); fuzzBounds<sw::lv16::Processor>(sw::lv16::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: lv17") { fuzzBounds<sw::lv17::Processor>(sw::lv17::specs(), 17u); fuzzBounds<sw::lv17::Processor>(sw::lv17::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: md01") { fuzzBounds<sw::md01::Processor>(sw::md01::specs(), 17u); fuzzBounds<sw::md01::Processor>(sw::md01::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: md02") { fuzzBounds<sw::md02::Processor>(sw::md02::specs(), 17u); fuzzBounds<sw::md02::Processor>(sw::md02::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: md03") { fuzzBounds<sw::md03::Processor>(sw::md03::specs(), 17u); fuzzBounds<sw::md03::Processor>(sw::md03::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: ms01") { fuzzBounds<sw::ms01::Processor>(sw::ms01::specs(), 17u); fuzzBounds<sw::ms01::Processor>(sw::ms01::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: ms02") { fuzzBounds<sw::ms02::Processor>(sw::ms02::specs(), 17u); fuzzBounds<sw::ms02::Processor>(sw::ms02::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: ms03") { fuzzBounds<sw::ms03::Processor>(sw::ms03::specs(), 17u); fuzzBounds<sw::ms03::Processor>(sw::ms03::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: ms04") { fuzzBounds<sw::ms04::Processor>(sw::ms04::specs(), 17u); fuzzBounds<sw::ms04::Processor>(sw::ms04::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: ms05") { fuzzBounds<sw::ms05::Processor>(sw::ms05::specs(), 17u); fuzzBounds<sw::ms05::Processor>(sw::ms05::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: ms06") { fuzzBounds<sw::ms06::Processor>(sw::ms06::specs(), 17u); fuzzBounds<sw::ms06::Processor>(sw::ms06::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: ms07") { fuzzBounds<sw::ms07::Processor>(sw::ms07::specs(), 17u); fuzzBounds<sw::ms07::Processor>(sw::ms07::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: rv01") { fuzzBounds<sw::rv01::Processor>(sw::rv01::specs(), 17u); fuzzBounds<sw::rv01::Processor>(sw::rv01::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: rv02") { fuzzBounds<sw::rv02::Processor>(sw::rv02::specs(), 17u); fuzzBounds<sw::rv02::Processor>(sw::rv02::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: rv03") { fuzzBounds<sw::rv03::Processor>(sw::rv03::specs(), 17u); fuzzBounds<sw::rv03::Processor>(sw::rv03::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: rv04") { fuzzBounds<sw::rv04::Processor>(sw::rv04::specs(), 17u); fuzzBounds<sw::rv04::Processor>(sw::rv04::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: rv05") { fuzzBounds<sw::rv05::Processor>(sw::rv05::specs(), 17u); fuzzBounds<sw::rv05::Processor>(sw::rv05::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: rv06") { fuzzBounds<sw::rv06::Processor>(sw::rv06::specs(), 17u); fuzzBounds<sw::rv06::Processor>(sw::rv06::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: rv07") { fuzzBounds<sw::rv07::Processor>(sw::rv07::specs(), 17u); fuzzBounds<sw::rv07::Processor>(sw::rv07::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: rv08") { fuzzBounds<sw::rv08::Processor>(sw::rv08::specs(), 17u); fuzzBounds<sw::rv08::Processor>(sw::rv08::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: sa01") { fuzzBounds<sw::sa01::Processor>(sw::sa01::specs(), 17u); fuzzBounds<sw::sa01::Processor>(sw::sa01::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: sa02") { fuzzBounds<sw::sa02::Processor>(sw::sa02::specs(), 17u); fuzzBounds<sw::sa02::Processor>(sw::sa02::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: sa03") { fuzzBounds<sw::sa03::Processor>(sw::sa03::specs(), 17u); fuzzBounds<sw::sa03::Processor>(sw::sa03::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: sa04") { fuzzBounds<sw::sa04::Processor>(sw::sa04::specs(), 17u); fuzzBounds<sw::sa04::Processor>(sw::sa04::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: sa05") { fuzzBounds<sw::sa05::Processor>(sw::sa05::specs(), 17u); fuzzBounds<sw::sa05::Processor>(sw::sa05::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: sa06") { fuzzBounds<sw::sa06::Processor>(sw::sa06::specs(), 17u); fuzzBounds<sw::sa06::Processor>(sw::sa06::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: sa07") { fuzzBounds<sw::sa07::Processor>(sw::sa07::specs(), 17u); fuzzBounds<sw::sa07::Processor>(sw::sa07::specs(), 29u); }
TEST_CASE("fuzz parameter bounds: sa08") { fuzzBounds<sw::sa08::Processor>(sw::sa08::specs(), 17u); fuzzBounds<sw::sa08::Processor>(sw::sa08::specs(), 29u); }
