#!/usr/bin/env python3
"""Turns ui/sw-ui.css, ui/sw-ui.js, ui/host.js and ui/products.json into one C++ header (byte arrays: MSVC refuses long string literals).
usage: tools/embed_ui.py <output.hpp>"""
import json, pathlib, sys
root = pathlib.Path(__file__).resolve().parent.parent
out = pathlib.Path(sys.argv[1])
def arr(name, data: bytes):
    rows = []
    for i in range(0, len(data), 24):
        rows.append(",".join(str(b) for b in data[i:i + 24]))
    return f"static const unsigned char {name}[] = {{\n" + ",\n".join(rows) + f"}};\nstatic const unsigned long {name}Size = {len(data)};\n"
parts = ["// generated by tools/embed_ui.py — do not edit", "#pragma once", "namespace sw::gui_assets {"]
parts.append(arr("kCss", (root / "ui/sw-ui.css").read_bytes()))
parts.append(arr("kJs", (root / "ui/sw-ui.js").read_bytes()))
parts.append(arr("kHostJs", (root / "ui/host.js").read_bytes()))
prod = json.loads((root / "ui/products.json").read_text())
items = []
for code, v in sorted(prod.items()):
    j = json.dumps(v, ensure_ascii=False, separators=(",", ":")).encode()
    items.append((code, j))
for i, (code, j) in enumerate(items):
    parts.append(arr(f"kMeta{i}", j))
parts.append("struct Meta { const char* code; const unsigned char* json; unsigned long size; };")
parts.append("static const Meta kMeta[] = {" + ",".join(f'{{"{c}", kMeta{i}, kMeta{i}Size}}' for i, (c, _) in enumerate(items)) + "};")
parts.append(f"static const int kMetaCount = {len(items)};")
parts.append("}  // namespace sw::gui_assets")
out.parent.mkdir(parents=True, exist_ok=True)
text = "\n".join(parts) + "\n"
if not out.exists() or out.read_text() != text: out.write_text(text)
