#!/usr/bin/env python3
"""SWINGBY (SW IN07) plug-in window: ui/in07 (manifest.json: the stylesheet, the scripts in order, the pictures and fonts) as one C++ header
of byte arrays (MSVC refuses long string literals). The page is small; the pictures and fonts go to it one by one after it is up
(plugin/clap/inst_gui.hpp: "c asset <i>"), so a WebView2 page stays far under its 2 MB limit.
usage: tools/embed_in07_ui.py <output.hpp>"""
import json, pathlib, sys

root = pathlib.Path(__file__).resolve().parent.parent
out = pathlib.Path(sys.argv[1])
man = json.loads((root / 'ui/in07/manifest.json').read_text())
MIME = {'.webp': 'image/webp', '.svg': 'image/svg+xml', '.png': 'image/png', '.woff2': 'font/woff2'}


def arr(name, data: bytes):
    rows = [','.join(str(b) for b in data[i:i + 32]) for i in range(0, len(data), 32)]
    return f'static const unsigned char {name}[] = {{\n' + ',\n'.join(rows or ['0']) + f'}};\nstatic const unsigned long {name}Size = {len(data)};\n'


js = b''
for s in man['scripts']:
    js += (root / s).read_bytes() + b'\n'
for s in [man['css']] + man['scripts']:
    if b'</script' in (root / s).read_bytes().lower() or b'</style' in (root / s).read_bytes().lower():
        sys.exit(f'{s}: a closing script or style tag would end the page early')
parts = ['// generated by tools/embed_in07_ui.py from ui/in07 — do not edit', '#pragma once', '#include "inst_gui.hpp"', 'namespace sw::in07ui {']
parts.append(arr('kCss', (root / man['css']).read_bytes()))
parts.append(arr('kJs', js))
names = []
for i, (name, path) in enumerate(man['assets'].items()):
    p = root / path
    parts.append(arr(f'kAsset{i}', p.read_bytes()))
    names.append((name, MIME[p.suffix], i))
parts.append('static const sw::instgui::Asset kAssets[] = {' + ','.join(f'{{"{n}", "{m}", kAsset{i}, kAsset{i}Size}}' for n, m, i in names) + '};')
parts.append(f'static const int kAssetCount = {len(names)};')
parts.append('}  // namespace sw::in07ui')
text = '\n'.join(parts) + '\n'
out.parent.mkdir(parents=True, exist_ok=True)
if not out.exists() or out.read_text() != text:
    out.write_text(text)
