#!/usr/bin/env python3
"""Regenerate tests/test_fuzz_bounds.cpp: every product's parameters set to their minimum / maximum (as clap-validator's param-fuzz-bounds does)
and a few buffers of noise through the core; the output must stay finite. Run after adding a product (tools/newplugin.py does)."""
import re, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
codes = re.search(r"set\(SW_PRODUCTS ([^)]*)\)", (root / "CMakeLists.txt").read_text()).group(1).split()
codes = sorted(c for c in codes)
out = ['// generated by tools/gen_fuzz.py: do not edit by hand', '#include "doctest.h"', '#include "tu.hpp"', '#include <random>', '#include <type_traits>']
out += [f'#include "{c}/{c}.hpp"' for c in codes]
out.append('''
namespace {
template <class C, class = void> struct HasTempo : std::false_type {};
template <class C> struct HasTempo<C, std::void_t<decltype(std::declval<C&>().setTempo(120.0))>> : std::true_type {};
template <class C, class = void> struct HasSc : std::false_type {};
template <class C> struct HasSc<C, std::void_t<decltype(std::declval<C&>().processWithSidechain(std::declval<float**>(), 0, 0, std::declval<const float* const*>(), 0))>> : std::true_type {};

// parameters at their ends (and the steps), a few buffers of noise, several rounds: the output must stay finite and sane
template <class P> void fuzzBounds(const std::vector<sw::ParamSpec>& specs, unsigned seed) {
    std::mt19937 rng(seed);
    for (double fs : {44100.0, 48000.0}) {
        P p;
        p.prepare(fs, 256);
        if constexpr (HasTempo<P>::value) p.setTempo(97.0);
        std::vector<float> l(256), r(256);
        for (int round = 0; round < 10; ++round) {
            for (size_t i = 0; i < specs.size(); ++i) {
                double v = (rng() & 1) ? specs[i].max : specs[i].min;
                if (specs[i].curve == sw::Curve::Step) v = specs[i].steps[rng() % specs[i].steps.size()];
                p.setParam(static_cast<int>(i), v);
            }
            if (round == 0) p.snapToTargets();
            for (int b = 0; b < 3; ++b) {
                for (int i = 0; i < 256; ++i) { l[static_cast<size_t>(i)] = static_cast<float>(std::uniform_real_distribution<>(-1, 1)(rng)); r[static_cast<size_t>(i)] = l[static_cast<size_t>(i)] * 0.5f; }
                float* c[2] = {l.data(), r.data()};
                if constexpr (HasSc<P>::value) { const float* sc[2] = {r.data(), l.data()}; p.processWithSidechain(c, 2, 256, sc, 2); }
                else p.process(c, 2, 256);
                for (int i = 0; i < 256; ++i) { REQUIRE(std::isfinite(l[static_cast<size_t>(i)])); REQUIRE(std::isfinite(r[static_cast<size_t>(i)])); REQUIRE(std::abs(l[static_cast<size_t>(i)]) < 1e10f); }
            }
        }
    }
}
}
''')
for c in codes:
    out.append(f'TEST_CASE("fuzz parameter bounds: {c}") {{ fuzzBounds<sw::{c}::Processor>(sw::{c}::specs(), 17u); fuzzBounds<sw::{c}::Processor>(sw::{c}::specs(), 29u); }}')
(root / "tests" / "test_fuzz_bounds.cpp").write_text("\n".join(out) + "\n")
print(f"{len(codes)} products")

# ---- tests/test_no_alloc.cpp: the audio thread does not allocate (CLAUDE.md): every product runs blocks with parameters changing in the middle, under tests/alloc_guard.hpp
out = ['// generated by tools/gen_fuzz.py: do not edit by hand', '#include "doctest.h"', '#include "alloc_guard.hpp"', '#include "tu.hpp"', '#include <random>', '#include <type_traits>']
out += [f'#include "{c}/{c}.hpp"' for c in codes]
out.append('''
namespace {
template <class C, class = void> struct HasTempo : std::false_type {};
template <class C> struct HasTempo<C, std::void_t<decltype(std::declval<C&>().setTempo(120.0))>> : std::true_type {};
template <class C, class = void> struct HasSc : std::false_type {};
template <class C> struct HasSc<C, std::void_t<decltype(std::declval<C&>().processWithSidechain(std::declval<float**>(), 0, 0, std::declval<const float* const*>(), 0))>> : std::true_type {};
template <class C, class = void> struct HasReset : std::false_type {};
template <class C> struct HasReset<C, std::void_t<decltype(std::declval<C&>().reset())>> : std::true_type {};
template <class C, class = void> struct HasTail : std::false_type {};
template <class C> struct HasTail<C, std::void_t<decltype(std::declval<const C&>().tailSeconds())>> : std::true_type {};
template <class C, class = void> struct HasWrites : std::false_type {};
template <class C> struct HasWrites<C, std::void_t<decltype(std::declval<C&>().takeParamWrite(std::declval<int&>(), std::declval<double&>()))>> : std::true_type {};

// prepare, two blocks to start, then (counted) rounds of: a few parameters set to values anywhere in their range (the adapter sets them on the audio thread), four blocks of noise (with a sidechain where the product has one)
template <class P> long allocations(const std::vector<sw::ParamSpec>& specs, unsigned seed, double fs) {
    std::mt19937 rng(seed);
    P p; p.prepare(fs, 256);
    if constexpr (HasTempo<P>::value) p.setTempo(97.0);
    p.snapToTargets();
    std::vector<float> l(256), r(256);
    auto block = [&]() {
        for (int i = 0; i < 256; ++i) { l[static_cast<size_t>(i)] = static_cast<float>(std::uniform_real_distribution<>(-0.5, 0.5)(rng)); r[static_cast<size_t>(i)] = l[static_cast<size_t>(i)] * 0.5f; }
        float* c[2] = {l.data(), r.data()};
        if constexpr (HasSc<P>::value) { const float* sc[2] = {r.data(), l.data()}; p.processWithSidechain(c, 2, 256, sc, 2); }
        else p.process(c, 2, 256);
    };
    block(); block();
    allocguard::Scope guard;
    for (int round = 0; round < 60; ++round) {
        for (int k = 0; k < 4; ++k) {
            const size_t i = rng() % specs.size();
            double v = specs[i].min + (specs[i].max - specs[i].min) * std::uniform_real_distribution<>(0, 1)(rng);
            if (specs[i].curve == sw::Curve::Step) v = specs[i].steps[rng() % specs[i].steps.size()];
            p.setParam(static_cast<int>(i), v);
        }
        for (int b = 0; b < 4; ++b) block();
        // what the adapter also does on the audio thread: the write queue, the tail, a reset (the host stopped or jumped)
        if constexpr (HasWrites<P>::value) { int id; double v; while (p.takeParamWrite(id, v) != 0) {} }
        if constexpr (HasTail<P>::value) { volatile double t = p.tailSeconds(); (void)t; }
        if constexpr (HasReset<P>::value) { if (round % 7 == 3) p.reset(); }
    }
    return guard.n();
}
}
''')
for c in codes:
    out.append(f'TEST_CASE("the audio thread does not allocate: {c}") {{ CHECK(allocations<sw::{c}::Processor>(sw::{c}::specs(), 5u, 48000.0) == 0); CHECK(allocations<sw::{c}::Processor>(sw::{c}::specs(), 9u, 96000.0) == 0); }}')
(root / "tests" / "test_no_alloc.cpp").write_text("\n".join(out) + "\n")
print("tests/test_no_alloc.cpp")

