#!/usr/bin/env python3
"""Regenerate tests/test_fuzz_bounds.cpp: every product's parameters set to their minimum / maximum (as clap-validator's param-fuzz-bounds does)
and a few buffers of noise through the core; the output must stay finite. Run after adding a product (tools/newplugin.py does)."""
import re, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
codes = re.search(r"set\(SW_PRODUCTS ([^)]*)\)", (root / "CMakeLists.txt").read_text()).group(1).split()
codes = sorted(c for c in codes)
out = ['// generated by tools/gen_fuzz.py: do not edit by hand', '#include "doctest.h"', '#include "tu.hpp"', '#include <random>', '#include <type_traits>']
out += [f'#include "{c}/{c}.hpp"' for c in codes]
out.append('''
namespace {
template <class C, class = void> struct HasTempo : std::false_type {};
template <class C> struct HasTempo<C, std::void_t<decltype(std::declval<C&>().setTempo(120.0))>> : std::true_type {};
template <class C, class = void> struct HasSc : std::false_type {};
template <class C> struct HasSc<C, std::void_t<decltype(std::declval<C&>().processWithSidechain(std::declval<float**>(), 0, 0, std::declval<const float* const*>(), 0))>> : std::true_type {};

// parameters at their ends (and the steps), a few buffers of noise, several rounds: the output must stay finite and sane
template <class P> void fuzzBounds(const std::vector<sw::ParamSpec>& specs, unsigned seed) {
    std::mt19937 rng(seed);
    for (double fs : {44100.0, 48000.0}) {
        P p;
        p.prepare(fs, 256);
        if constexpr (HasTempo<P>::value) p.setTempo(97.0);
        std::vector<float> l(256), r(256);
        for (int round = 0; round < 10; ++round) {
            for (size_t i = 0; i < specs.size(); ++i) {
                double v = (rng() & 1) ? specs[i].max : specs[i].min;
                if (specs[i].curve == sw::Curve::Step) v = specs[i].steps[rng() % specs[i].steps.size()];
                p.setParam(static_cast<int>(i), v);
            }
            if (round == 0) p.snapToTargets();
            for (int b = 0; b < 3; ++b) {
                for (int i = 0; i < 256; ++i) { l[static_cast<size_t>(i)] = static_cast<float>(std::uniform_real_distribution<>(-1, 1)(rng)); r[static_cast<size_t>(i)] = l[static_cast<size_t>(i)] * 0.5f; }
                float* c[2] = {l.data(), r.data()};
                if constexpr (HasSc<P>::value) { const float* sc[2] = {r.data(), l.data()}; p.processWithSidechain(c, 2, 256, sc, 2); }
                else p.process(c, 2, 256);
                for (int i = 0; i < 256; ++i) { REQUIRE(std::isfinite(l[static_cast<size_t>(i)])); REQUIRE(std::isfinite(r[static_cast<size_t>(i)])); REQUIRE(std::abs(l[static_cast<size_t>(i)]) < 1e10f); }
            }
        }
    }
}
}
''')
for c in codes:
    out.append(f'TEST_CASE("fuzz parameter bounds: {c}") {{ fuzzBounds<sw::{c}::Processor>(sw::{c}::specs(), 17u); fuzzBounds<sw::{c}::Processor>(sw::{c}::specs(), 29u); }}')
(root / "tests" / "test_fuzz_bounds.cpp").write_text("\n".join(out) + "\n")
print(f"{len(codes)} products")
