#!/usr/bin/env python3
"""Regenerate core/include/sw/link_products.hpp: the products an SW Link source can be (code + the name after "SW "), in the order of CMakeLists.txt's sw_add_plugin lines.
Used by the parameters that pick a source (VO05 "Music from", LV29 "Interp from"). Run after adding a product."""
import re, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
rows = re.findall(r'sw_add_plugin\((\w+) "SW (\w+) ([^"]+)"', (root / "CMakeLists.txt").read_text())
rows = sorted({(c.upper(), f"{c.upper()} {n}") for c, _, n in rows if True})
out = ['// generated by tools/gen_link_products.py: do not edit by hand', '// the products an SW Link source can be: the code and the name the screen shows ("LV01 Voice"), sorted by code',
       '#pragma once', '#include <cstddef>', '', 'namespace sw {', '', 'struct LinkProduct { const char* code; const char* label; };', '',
       'inline const LinkProduct* linkProducts(size_t& n) {', '    static const LinkProduct k[] = {']
out += [f'        {{"{c}", "{l}"}},' for c, l in rows]
out += ['    };', '    n = sizeof(k) / sizeof(k[0]);', '    return k;', '}', '', '}  // namespace sw', '']
(root / "core" / "include" / "sw" / "link_products.hpp").write_text("\n".join(out))
print(len(rows), "products")
